### ISSUE TITLE
Live Preview not working for nested class names (BEM CSS) when preceded by nested property

### ISSUE THREAD

**Issue by joakimc** [jasonsanjose/brackets-sass#189]
I just discovered that Live Preview doesn't work for nested class-names when preceded by something like this:

```scss
padding: {
  left: 20px;
  right: 20px; }
```

Here's the complete code for this block, which doesn't work with Live Preview unless removing the piece above:

```scss
.section {
  @include padding-v(6);
  @include section-background;
  font-size: $font-size-copy;
  padding: {
    left: 20px;
    right: 20px; }
  .title {
    margin-top: 0;
    font-size: $font-size-title;
    text-align: center; }
  &__container {
    max-width: $content-width;
    @include push--auto;
    > *:last-child {
      margin-bottom: 0; }
    &--announcement {
      width: 800px;
      padding: $space-unit * 2;
      background-color: $color-white;
      @include shadow-subtle;
      .title {
        color: $color-main;
        @include border;
        font-family: $font-titles-big;
        line-height: 1.2em;
        text-transform: uppercase;
        margin: 0; }
      .content {
        color: $color-main-dark;
        @include border;
        border-top: 0;
        *:first-child {
          margin-top: 0; }
        .button {
          margin-top: $space-unit;
        } } } }
  &:nth-child(even) {
    background: {
      color: $color-white;
      image: none; } }
}
```
