### ISSUE TITLE
Wrong line number on chrome sourcMapping

### ISSUE THREAD

**Issue by lucascosta** [jasonsanjose/brackets-sass#88]
Line numbers on Chrome always show the last line in the scss. Example:
```css
html {
	background: red;
}
body {
	background: blue;
}
```
Both the html and body background properties are mapped to **theme.scss:5**

My `.brackets.json`

```json
{
	"sass.enabled": true,
	"sass.options": {
		"outputDir": "../css/",
		"sourceComments": false,
		"outputStyle": "nested"
	}
}
```

I'm on Windows 8.
